{{% BLOCKS }}
{{<layout}}
{{$styles}}

{{/styles}}

{{$content}}
<br />
<div class="panel panel-default">

    <div class="panel-heading"><h3>Permissions</h3></div>

    <div class="panel-body">
        <div class="dataTable_wrapper">
            <table class="table table-striped table-bordered table-hover permission" id="dataTables-example">
                <thead>
                    <tr>
                        <th>Date Of Submission</th>
                        <th>Requester</th>
                        <th>From</th>
                        <th>To</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {{!template-with-dereferencing.mustache}}
                    {{#permissions}}
                    <tr>
                        <td><a href="/requests/permission/show/{{id}}">{{dateOfSubmission}}</a></td>
                        <td>{{user}}</td>
                        <td>{{fromTime}}</td>
                        <td>{{toTime}}</td>
                        <td>{{status}}</td>

                        <td>
                            {{#approveActionAllowed}}
                            <a href="/requests/myrequests/approve/{{id}}/Permission" class="btn btn-primary">Approve</a>
                            {{/approveActionAllowed}}

                            {{#declineActionAllowed}}
                            <a href="/requests/myrequests/decline/{{id}}/Permission" class="btn btn-success">Decline</a>
                            {{/declineActionAllowed}}

                            {{#cancelActionAllowed}}
                            <a href="/requests/myrequests/cancel/{{id}}/Permission" class="btn delete_row btn-danger">Cancel</a>
                            {{/cancelActionAllowed}}


                        </td>
                    </tr>
                    {{/permissions}}
                    </td>
                    </tr>

                </tbody>
            </table>
        </div>
    </div>
</div>

<br>
<div class="panel panel-default">

    <div class="panel-heading"><h3>Vacation Requests</h3></div>

    <div class="panel-body">
        <div class="dataTable_wrapper">
            <table class="table table-striped table-bordered table-hover vacation" id="dataTables-example">
                <thead>
                    <tr>
                        <th>Date Of Submission</th>
                        <th>Requester</th>
                        <th>From</th>
                        <th>To</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {{#vacationRequests}}
                    <tr>
                        <td><a href="/requests/vacation/show/{{id}}">{{dateOfSubmission}}</a></td>                
                        <td>{{user}}</td>
                        <td>{{fromDate}}</td>
                        <td>{{toDate}}</td>
                        <td>{{status}}</td>

                        <td>
                            {{#approveActionAllowed}}
                            <a href="/requests/myrequests/approve/{{id}}/VacationRequest" class="btn btn-primary">Approve</a>
                            {{/approveActionAllowed}}

                            {{#declineActionAllowed}}
                            <a href="/requests/myrequests/decline/{{id}}/VacationRequest" class="btn btn-success">Decline</a>
                            {{/declineActionAllowed}}

                            {{#cancelActionAllowed}}
                            <a href="/requests/myrequests/cancel/{{id}}/VacationRequest" class="btn delete_row btn-danger">Cancel</a>
                            {{/cancelActionAllowed}}


                        </td>
                    </tr>
                    {{/vacationRequests}}
                    </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<!--Work from home table-->

<br>
<div class="panel panel-default">

    <div class="panel-heading"><h3>Work from home Requests</h3></div>

    <div class="panel-body">
        <div class="dataTable_wrapper">
            <table class="table table-striped table-bordered table-hover workfromhome" id="dataTables-example">
                <thead>
                    <tr>
                        <th>Date Of Submission</th>
                        <th>Requester</th>
                        <th>From </th>
                        <th>To </th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {{#workFromHomeRequests}}
                    <tr>
                        <td><a href="/requests/workfromhome/show/{{id}}">{{dateOfSubmission}}</a></td>
                        <td>{{user}}</td>
                        <td>{{startDate}}</td>
                        <td>{{endDate}}</td>
                        <td>{{status}}</td>

<!--                <td><a href="delete/{{id}}" class="delete_row  btn btn-small btn-primary"> Deactivate</a>
                    &nbsp;<a href="edit/{{id}}" class="btn btn-small btn-warning" >Edit</a>
                </td>-->
                        <td>

                            {{#approveActionAllowed}}
                            <a href="/requests/myrequests/approve/{{id}}/WorkFromHome" class="btn btn-primary">Approve</a>
                            {{/approveActionAllowed}}

                            {{#declineActionAllowed}}
                            <a href="/requests/myrequests/decline/{{id}}/WorkFromHome" class="btn btn-success">Decline</a>
                            {{/declineActionAllowed}}

                            {{#cancelActionAllowed}}
                            <a href="/requests/myrequests/cancel/{{id}}/WorkFromHome" class="btn delete_row btn-danger">Cancel</a>
                            {{/cancelActionAllowed}}

                        </td>
                    </tr>
                    {{/workFromHomeRequests}}
                    </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

{{/content}}

{{$scripts}}

{{/scripts}}

{{/layout}}