{{% BLOCKS }}
<!doctype html>
<html>

    <head>
        <title>Attendance System</title>
        <meta charset="UTF-8">

        <link rel="stylesheet" href="/concat/app{{#isProduction}}.min{{/isProduction}}.css" />
        <!-- Additional styles to be added to specific views -->
        {{$styles}}{{/styles}}

    </head>

    <body>

        <div id="wrapper">

            <!-- Navigation -->
            <nav class="navbar navbar-default navbar-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/index">Attendance HUB</a>
                </div>
                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav in" id="side-menu">
                            <li>
                                <h3><i class="fa fa-dashboard fa-fw"></i> Dashboard</h3>
                            </li>
                            {{#visibleUserModule}}
                            <!--Users Module-->
                            <li>
                                <a href="/users" id="users">Users  &nbsp;&nbsp;<i class="fa fa-user fa-fw"></i></a>
                            </li>
                            <!--Users Module-->
                            {{/visibleUserModule}}
                            <!--Settings Module-->
                            {{#visibleSettingsModule}}
                            <li>
                                <a href="#" id='settings' >Settings &nbsp;&nbsp;<i class="glyphicon  glyphicon-wrench fa-fw " ></i><span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level collapse">
                                    <li>
                                        <a href="/settings/vacation/index" id='vacation'>Vacation</a>
                                    </li>
                                    <li>
                                        <a href="/settings/holiday/index" id="holidays">Holidays</a>
                                    </li>
                                    <li>
                                        <a href="/settings/attendance/index" id="attendance">Attendance</a>
                                    </li>
                                    <li>
                                        <a href="/settings/position/index" id='positions'>Positions</a>
                                    </li>
                                    <li>
                                        <a href="/settings/departments/index"id="departments">Departments</a>
                                    </li>
                                    <li>
                                        <a href="/settings/branches/index" id="branches">Branches</a>
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            <!--Settings Module-->
                            {{/visibleSettingsModule}}
                            <!--Requests Module-->
                            <li>
                                <a href="#">Requests  &nbsp;&nbsp;<i class="glyphicon  glyphicon-send fa-fw " ></i><span class="fa  arrow  "></span></a>
                                <ul class="nav nav-second-level collapse">
                                    <li>
                                        <a href="/requests/myrequests/index">My Requests</a>
                                    </li>
                                    <li>
                                        <a href="/requests/permission/new">Permission</a>
                                    </li>
                                    <li>
                                        <a href="/requests/vacation/new">Vacation</a>
                                    </li>
                                    <li>
                                        <a href="/requests/workfromhome/new">Work From Home</a>
                                    </li>
                                </ul>
                            </li>

                            <!--my attendance-->
                            <!--Requests Module-->
                            <li>
                                <a href="#">My Attendance  &nbsp;&nbsp;<i class=" fa fa-file fa-fw " ></i><span class="fa  arrow  "></span></a>
                                <ul class="nav nav-second-level collapse">
                                    <li>
                                        <a href="/myattendance/attendance">My Attendance </a>
                                    </li>
                                    <li>
                                        <a href="/myattendance/vacation">My Vacations</a>
                                    </li>
                                    <li>
                                        <!--<a href="/requests/workfromhome/new">Work From Home</a>-->
                                    </li>
                                    <li>
                                        <!--<a href="/requests/myrequests/index">My Requests</a>-->
                                    </li>
                                </ul>
                            </li>
                            <!--my attendance--> 

                            <li>
                                {{#visible}}
                                <a href="/calendar">Holiday Calendar &nbsp;&nbsp;<i class="fa fa-calendar fa-fw " ></i></a>
                                {{/visible}} 
                            </li>
                            <li>
                                {{#visible}}
                                <a href="/notifications">Notifications &nbsp;&nbsp;<i class="fa fa-globe fa-fw " >{{#unseenNotificationsCount}}<div class='notification_count'>{{unseenNotificationsCount}}</div>{{/unseenNotificationsCount}}</i></a>
                                {{/visible}} 
                            </li>
                            <!--log out-->
                            <li>
                                {{#visible}}
                                <a href="/sign/out">Log out , Bye {{name}} &nbsp;&nbsp;<i class="glyphicon glyphicon-log-out fa-fw " ></i><span class="fa arrow"></span></a>
                                {{/visible}} 
                            </li>
                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
                <!-- /.navbar-static-side -->
            </nav>

            <div id="page-wrapper">

                <!-- /.row -->
                <div class="row">
                    <div class="col-lg-12">
                        {{$content}}{{/content}}  
                        <!-- /.panel-footer -->
                    </div>
                    <!-- /.panel .chat-panel -->
                </div>
                <!-- /.col-lg-4 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->








        <script src="/concat/app{{#isProduction}}.min{{/isProduction}}.js" type="text/javascript"></script>
        <!-- Additional scripts to be added to specific views -->
        {{$scripts}}{{/scripts}}

    </body>

</html>
