{{% BLOCKS }}

{{<layout}}
{{$content}}


<div class="container login-container redirect-deactivated active-redirect-error">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default" error-panel>
                <div class="panel-body">
                    <center>
                        you're Deactivated right now ... please call branch's admin to solve the problem.. you'll be redirected in 3 seconds
                    </center>
                </div>
            </div>
        </div>
    </div>
</div>

{{/content}}
{{/layout}}
