base:
  phpSettings:
    display_startup_errors: 1
    display_errors: 1
    html_errors: 1
    date:
      timezone: Africa/Cairo
  bootstrap:
    path: APPLICATION_PATH/Bootstrap.php
    class: Bootstrap
  appnamespace: Application
  autoloaderNamespaces:
    - CamelCaseTech
  includePaths:
    library: APPLICATION_PATH/../library
  pluginpaths:
    CamelCaseTech_Resource: CamelCaseTech/Resource
  resources:
    frontController:
      moduleDirectory: APPLICATION_PATH/modules
      params:
        displayExceptions: 1
        prefixDefaultModule: 1
    view:
    # No contents - "view" block required to instantiate "CamelCaseTech_Resource_View" resource
    db:
      adapter: pdo_mysql
      isDefaultTableAdapter: true
      params:
        host: localhost
        username: attendance
        password: attendance
        dbname: attendance

production:
  _extends: base

staging:
  _extends: base

testing:
  _extends: base

development:
  _extends: base

local:
  _extends: base